# Generated by Django 2.2 on 2020-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='pet_photo')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
